<?php

namespace App\DataFixtures\Provider;

class MyMenuProvider
{
    private $recipes = [
        "Spaghetti à la Carbonara",
        "Poulet rôti aux herbes",
        "Lasagnes végétariennes",
        "Bœuf bourguignon",
        "Pizza Margherita",
        "Risotto aux champignons",
        "Sushi au saumon",
        "Tacos au poulet",
        "Salade César",
        "Soupe à l'oignon gratinée",
        "Boulettes de viande suédoises",
        "Poulet tikka masala",
        "Crevettes à l'ail et au citron",
        "Burger végétarien",
        "Pain de viande",
        "Pâtes Alfredo",
        "Tarte aux pommes",
        "Moussaka",
        "Gumbo de crevettes",
        "Cannelloni aux épinards",
        "Pad thaï aux crevettes",
        "Poulet au curry",
        "Roulés au fromage et aux épinards",
        "Salade grecque",
        "Ratatouille",
        "Tarte au citron meringuée",
        "Chili con carne",
        "Cordon bleu de poulet",
        "Fajitas aux légumes",
        "Pancakes aux myrtilles",
        "Bouillabaisse",
        "Tofu sauté au sésame",
        "Crostini à la tomate",
        "Moules marinières",
        "Raviolis aux champignons",
        "Poulet à l'orange",
        "Quiche lorraine",
        "Pommes de terre au gratin",
        "Bœuf Stroganoff",
        "Poulet à la moutarde",
        "Riz frit aux légumes",
        "Salade de couscous",
        "Œufs bénédictine",
        "Tiramisu",
        "Escargots à l'ail",
        "Pain perdu",
        "Côtes levées BBQ",
        "Crevettes à la sauce créole",
        "Gâteau au chocolat fondant",
        "Tartare de saumon"
    ];

    private $categories = [
        "Plats de viande",
        "Plats végétariens",
        "Cuisine italienne",
        "Cuisine française",
        "Cuisine mexicaine",
        "Cuisine asiatique",
        "Cuisine indienne",
        "Cuisine méditerranéenne",
        "Salades",
        "Desserts"
    ];

    private $ingredients = [
        "Poulet",
        "Herbes",
        "Lasagnes",
        "Bœuf",
        "Pâte à pizza",
        "Champignons",
        "Saumon",
        "Tortillas",
        "Laitue romaine",
        "Oignons",
        "Boulettes de viande",
        "Sauce tikka masala",
        "Crevettes",
        "Ail",
        "Pain à burger",
        "Riz",
        "Citron",
        "Fromage feta",
        "Aubergines",
        "Crevettes",
        "Cannelloni",
        "Nouilles de riz",
        "Épinards",
        "Feta",
        "Poivron rouge",
        "Curry en poudre",
        "Fromage à la crème",
        "Tomates",
        "Haricots rouges",
        "Poitrine de poulet",
        "Crème fraîche",
        "Pommes de terre",
        "Bouillon de poulet",
        "Viande hachée",
        "Moules",
        "Raviolis",
        "Oranges",
        "Oeufs",
        "Bacon",
        "Pâtes",
        "Parmesan",
        "Thym",
        "Piment",
        "Cannelle",
        "Aubergines",
        "Huile d'olive",
        "Pain",
        "Ail",
        "Persil",
        "Côtes levées",
        "Crème",
        "Cumin",
        "Paprika",
        "Poivre noir",
        "Poivron vert",
        "Légumes",
        "Basilic",
        "Fromage ricotta",
        "Sauce tomate",
        "Bouillon de légumes",
        "Sauce soja",
        "Sauce Worcestershire",
        "Oignons verts",
        "Cidre",
        "Beurre",
        "Carottes",
        "Oignons",
        "Courgettes",
        "Chorizo",
        "Thon",
        "Parmesan râpé",
        "Pain de mie",
        "Crème aigre",
        "Noix de muscade",
        "Fromage cheddar",
        "Câpres",
        "Basilic frais",
        "Vin rouge",
        "Crème épaisse",
        "Moutarde de Dijon",
        "Cerfeuil",
        "Cornichons",
        "Crème fouettée",
        "Menthe",
        "Poivrons rouges",
        "Échalotes",
        "Épinards frais",
        "Pâte feuilletée",
        "Bouillon de boeuf",
        "Parmesan frais",
        "Poivre de Cayenne",
        "Lait",
        "Basilic séché",
        "Sucre",
        "Écorce de citron",
        "Farine",
        "Fromage mozzarella",
        "Aubergine",
        "Concombre",
        "Coriandre",
        "Raisins secs",
        "Sauce chili",
        "Sauce hoisin",
        "Mangue",
        "Beurre d'arachide",
        "Gingembre frais",
        "Poudre de chili",
        "Sauce Sriracha",
        "Avocat",
        "Cacahuètes",
        "Lait de coco",
        "Curry rouge",
        "Poitrine de porc",
        "Gruyère",
        "Biscuits Graham",
        "Cacao en poudre",
        "Chocolat noir",
        "Mascarpone",
        "Amandes effilées",
        "Sirop d'érable",
        "Crème pâtissière",
        "Poudre d'amande",
        "Jambon",
        "Ananas",
        "Pâte à tarte",
        "Huile de sésame",
        "Menthe fraîche",
        "Sauce teriyaki",
        "Piments jalapeños",
        "Cerises",
        "Raisins",
        "Sucre en poudre",
        "Vin blanc",
        "Oignons rouges",
        "Piment de Cayenne",
        "Lait évaporé",
        "Poudre de cacao",
        "Saumon fumé",
        "Huile de canola",
        "Oignons caramélisés",
        "Aneth",
        "Vinaigre balsamique",
        "Fromage suisse",
        "Pistaches",
        "Pâte phyllo",
        "Champignons sauvages",
        "Boulettes de porc",
        "Sauce barbecue",
        "Gingembre moulu",
        "Noix de cajou",
    ];

    /**
    * Retourne une recette au hasard
    */
    public function recipeName()
    {
        return $this->recipes[array_rand($this->recipes)];
    }

    /**
    * Retourne une categorie au hasard
    */
    public function recipeCategory()
    {
        return $this->categories[array_rand($this->categories)];
    }

    /**
    * Retourne un ingredient au hasard
    */
    public function recipeIngredients()
    {
        return $this->ingredients[array_rand($this->ingredients)];
    }

}